import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Terms of Use - TypeMate",
  description: "The terms under which the TypeMate apps are provided.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Use" updated="27 August 2026">
      <p>
        These terms apply to the TypeMate apps for Windows, macOS, Linux, and
        Android, and to the website typemate.codewalnut.com, all provided by{" "}
        <a href="https://www.codewalnut.com" target="_blank" rel="noreferrer">
          CodeWalnut
        </a>
        . By installing or using TypeMate you agree to these terms.
      </p>

      <h2>License</h2>
      <p>
        TypeMate is free to use. It is proprietary software owned by
        CodeWalnut. We grant you a personal, non-transferable right to
        install and use the app on your devices. You may not copy, modify,
        redistribute, sell, or reverse engineer the app, except where
        applicable law allows it despite this restriction. The TypeMate
        name and logo remain the property of CodeWalnut.
      </p>

      <h2>Acceptable use</h2>
      <p>
        You agree not to use TypeMate to violate any law, to infringe the
        rights of others, or to attempt to disrupt the services the app
        relies on (such as the model download hosting).
      </p>

      <h2>Third-party components</h2>
      <p>
        TypeMate bundles and downloads open-source components and speech
        models, each covered by its own license. Those licenses apply to
        the respective components, not to TypeMate itself.
      </p>

      <h2>No warranty</h2>
      <p>
        TypeMate is provided <strong>&quot;as is&quot;</strong>, without
        warranty of any kind, express or implied, including fitness for a
        particular purpose. Transcription output is generated by automatic
        speech recognition and may contain errors; you are responsible for
        reviewing what gets typed on your behalf.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, CodeWalnut shall not be
        liable for any indirect, incidental, special, or consequential
        damages arising from the use of, or inability to use, TypeMate.
      </p>

      <h2>Changes</h2>
      <p>
        We may update these terms from time to time. The current version
        always lives at this page with its date above. Continued use of the
        app after a change constitutes acceptance of the new terms.
      </p>

      <h2>Governing law</h2>
      <p>
        These terms are governed by the laws of India, without regard to
        conflict-of-law principles.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms? Reach us through{" "}
        <a href="https://www.codewalnut.com" target="_blank" rel="noreferrer">
          codewalnut.com
        </a>{" "}
        or open an issue on{" "}
        <a
          href="https://github.com/CW-Codewalnut/typemate/issues"
          target="_blank"
          rel="noreferrer"
        >
          GitHub
        </a>
        .
      </p>
    </LegalPage>
  );
}
